# NumPy学习

## NumPy简介

NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。
NumPy 的前身 Numeric 最早是由 Jim Hugunin 与其它协作者共同开发，2005 年，Travis Oliphant 在 Numeric 中结合了另一个同性质的程序库 Numarray 的特色，并加入了其它扩展而开发了 NumPy。NumPy 为开放源代码并且由许多协作者共同维护开发。

NumPy 是一个运行速度非常快的数学库，主要用于数组计算，包含：

* 一个强大的N维数组对象 ndarray
* 广播功能函数
* 整合 C/C++/Fortran 代码的工具
* 线性代数、傅里叶变换、随机数生成等功能

PS:#加空格代表标题  *加空格为斜体，两个*为加粗

## NumPy应用

NumPy 通常与 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用， 这种组合广泛用于替代 MatLab，是一个强大的科学计算环境，有助于我们通过 Python 学习数据科学或者机器学习。

SciPy 是一个开源的 Python 算法库和数学工具包。

SciPy 包含的模块有最优化、线性代数、积分、插值、特殊函数、快速傅里叶变换、信号处理和图像处理、常微分方程求解和其他科学与工程中常用的计算。

Matplotlib 是 Python 编程语言及其数值数学扩展包 NumPy 的可视化操作界面。它为利用通用的图形用户界面工具包，如 Tkinter, wxPython, Qt 或 GTK+ 向应用程序嵌入式绘图提供了应用程序接口（API）。

## NumPy具体函数介绍

### Ndarray（array函数）

NumPy Ndarray 对象 ：NumPy 最重要的一个特点是其 N 维数组对象 ndarray，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。 ndarray 中的每个元素在内存中都有相同存储大小的区域。

ndarray 内部由以下内容组成： 

* 一个指向数据（内存或内存映射文件中的一块数据）的指针。
* 数据类型或 dtype，描述在数组中的固定大小值的格子。
* 一个表示数组形状（shape）的元组，表示各维度大小的元组。
* 一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。

ndarray 对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的一个位置。内存块以行顺序(C样式)或列顺序(FORTRAN或MatLab风格，即前述的F样式)来保存元素。

In [25]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])#排列法，中括号的嵌套数目代表数组的维度
print(a)

[[1 2 3]
 [4 5 6]]


### NumPy数据类型

https://www.runoob.com/numpy/numpy-dtype.html
详情查看相关的数据类型转换

In [26]:

import numpy as np
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt = np.dtype('i4')
print(dt)
# 'ix'可以使用8*x来进行计算


int32


### NumPy数组属性

NumPy 数组的维数称为秩（rank），秩就是轴的数量，即数组的维度，一维数组的秩为 1，二维数组的秩为 2，以此类推。轴数越小，跨越的元素数量越多。

在 NumPy中，每一个线性的数组称为是一个轴（axis），也就是维度（dimensions）。比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是 NumPy 中的轴（axis），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量——秩，就是数组的维数。

* *很多时候可以声明 axis。axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。*
* *值得注意的是，各个属性的操作可以直接以A.函数的形式使用，以下面为例！*

详情请见https://www.runoob.com/numpy/numpy-array-attributes.html


In [27]:

import numpy as np 
# ndim为求数组的秩，即轴的数量或维度的数量
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度 reshape为n行m列z轴，所以为一个三维数组
#注意n*m*z结果要为元素数量24
print (b.ndim)


1
3


ndarray.shape 表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。比如，一个二维数组，其维度表示"行数"和"列数"。
ndarray.shape 也可以用于调整数组大小。

In [28]:

import numpy as np  
#
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)


(2, 3)


reshape函数常用于调整数组的大小

In [ ]:

import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  
print (b)


In [17]:
import numpy as np
arr2d = np.arange(24).reshape((4,6))
print(arr2d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


查看数组内存信息，使用ndarray.flags函数

具体信息如下：

C_CONTIGUOUS (C) 	数据是在一个单一的C风格的连续段中 

F_CONTIGUOUS (F) 	数据是在一个单一的Fortran风格的连续段中

OWNDATA (O) 	数组拥有它所使用的内存或从另一个对象中借用它

WRITEABLE (W) 	数据区域可以被写入，将该值设置为 False，则数据为只读

ALIGNED (A) 	数据和所有元素都适当地对齐到硬件上

UPDATEIFCOPY (U) 	这个数组是其它数组的一个副本，当这个数组被释放时，原数组的内容将被更新

In [29]:

import numpy as np 
 
x = np.array([1,2,3,4,5])  
print (x.flags)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



### NumPy创建数组

In [21]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)#创建一个3行2列的数组，都是随机值，因为没有初始化


[[     1320         0]
 [     1320         0]
 [   131074 539769134]]


In [22]:
x = np.ones([2,2], dtype = int)
print(x)
y = np.zeros([2,2])
print(y)#默认为浮点型
z = np.zeros([2,2],dtype = int)
print(z)

[[1 1]
 [1 1]]
[[0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]]


### NumPy 从已有的数组创建数组 进行到这里了

In [18]:
type(arr2d)

numpy.ndarray

In [19]:
np.arange(2,8,2)#arange用法：2到8间隔为2左闭右开

array([2, 4, 6])

In [20]:
np.linspace(2,8,6)#linspace用法，2到8分成x个点左闭右闭

array([2. , 3.2, 4.4, 5.6, 6.8, 8. ])